/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbsencesIdRouteImport } from './routes/absences.$id'
import { Route as AbsencesNewRouteImport } from './routes/absences.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsencesIdRoute = AbsencesIdRouteImport.update({
  id: '/absences/$id',
  path: '/absences/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsencesNewRoute = AbsencesNewRouteImport.update({
  id: '/absences/new',
  path: '/absences/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absences/$id': typeof AbsencesIdRoute
  '/absences/new': typeof AbsencesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absences/$id': typeof AbsencesIdRoute
  '/absences/new': typeof AbsencesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/absences/$id': typeof AbsencesIdRoute
  '/absences/new': typeof AbsencesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/absences/$id' | '/absences/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/absences/$id' | '/absences/new'
  id: '__root__' | '/' | '/absences/$id' | '/absences/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbsencesIdRoute: typeof AbsencesIdRoute
  AbsencesNewRoute: typeof AbsencesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absences/$id': {
      id: '/absences/$id'
      path: '/absences/$id'
      fullPath: '/absences/$id'
      preLoaderRoute: typeof AbsencesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absences/new': {
      id: '/absences/new'
      path: '/absences/new'
      fullPath: '/absences/new'
      preLoaderRoute: typeof AbsencesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbsencesIdRoute: AbsencesIdRoute,
  AbsencesNewRoute: AbsencesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
